version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/template-nextjs"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/template-react"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/template-vanilla"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/template-vanilla-ts"
    schedule:
      interval: "daily"
